/* Generated by scripts/build-sw.mjs. Do not edit. */
const CACHE = 'steelsquall-7104f73c884e';
const PRECACHE = [
  "./",
  "./app.webmanifest",
  "./assets/index-Bb1CZTY5.js",
  "./icon-192.png",
  "./icon-512.png",
  "./index.html"
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    // cache: 'reload' skips the browser's HTTP cache. Without it an update can store the
    // previous build's index.html (GitHub Pages lets browsers keep files for 10 minutes),
    // leaving the phone stuck on the old version under the new worker.
    caches.open(CACHE)
      .then((cache) => cache.addAll(PRECACHE.map((u) => new Request(u, { cache: 'reload' }))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

/*
 * Opening the game (a navigation) tries the network first, so an online launch always
 * gets the newest page; with no network, or after 3 seconds of weak signal, it falls
 * back to the stored page. Everything else is cache-first: the game ships all of its
 * content in the bundle and makes no runtime requests of its own.
 */
function shell(request) {
  return caches.match(request, { ignoreSearch: true }).then((hit) => hit || caches.match('./index.html'));
}
self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    const network = fetch(request, { cache: 'no-store' }).then((r) => (r && r.ok ? r : Promise.reject(r)));
    const timeout = new Promise((_, reject) => setTimeout(reject, 3000));
    event.respondWith(Promise.race([network, timeout]).catch(() => shell(request)));
    return;
  }

  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(request)
        .then((response) => {
          if (response && response.status === 200 && response.type === 'basic') {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => {
          if (request.mode === 'navigate') return caches.match('./index.html');
          return Response.error();
        });
    })
  );
});
